### ISSUE TITLE
Not work Android 7.1

### ISSUE THREAD

**Issue by Alexey71** [JoshuaWebb/BatteryNotificationMod#1]
Hello. Module good. Please update

[xposed_error_20171009_142018.txt](https://github.com/JoshuaWebb/BatteryNotificationMod/files/1368276/xposed_error_20171009_142018.txt)

**Comment by JoshuaWebb** [comment]
I made a version a while ago trying to investigate compatibility for other devices, can you please give that a try?

https://github.com/JoshuaWebb/BatteryNotificationMod/releases/tag/0.2.0-alpha

**Comment by Alexey71** [comment]
Not work, I install other module. Thx
